"""Add is_favorite to matches

Revision ID: 234087b03c66
Revises: 005_crawl_logs
Create Date: 2026-02-01 09:01:53.860385

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '234087b03c66'
down_revision: Union[str, None] = '005_crawl_logs'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_favorite', sa.Boolean(), nullable=False, server_default='0'))
        batch_op.create_index(batch_op.f('ix_matches_is_favorite'), ['is_favorite'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_matches_is_favorite'))
        batch_op.drop_column('is_favorite')

    # ### end Alembic commands ###
